### ISSUE TITLE
eval_img is None when selecting hard negative examples

### ISSUE THREAD

**Issue by freshn** [IIM-TTIJ/MVA2023SmallObjectDetection4SpottingBirds#12]
Hi. I met a bug selecting hard negative examples. When I ran Step 3 in dist_train_test.sh on my customized method, it failed with error messages:

Traceback (most recent call last):  
  File "hard_neg_example_tools/test_hard_neg_example.py", line 315, in <module>  
    main()  
  File "hard_neg_example_tools/test_hard_neg_example.py", line 291, in main  
    **hard_negative_config,
  File "/home/repo/MVA2023SmallObjectDetection4SpottingBirds/mmdet/datasets/drone.py", line 330, in generate_hard_negatives
    max_det=num_max_det)
  File "/home/repo/MVA2023SmallObjectDetection4SpottingBirds/mmdet/datasets/drone.py", line 360, in identify_hard_negatives
    for i in range(len(eval_img['dtIds'])):  # det are sorted by scores from high to low
TypeError: 'NoneType' object is not subscriptable

It seems the eval_img is set to None by mistake. I have no idea why this will happen. Could you help me with this?

**Comment by cyoukaikai** [comment]
Thanks for posting the issue. We are investigating the issue now.

**Comment by cyoukaikai** [comment]
Issue: eval_img['dtIds'] is 'NoneType'
One possible reason is that your predictions are somehow invalid so predictions are empty. 
Would you please check 
1) you do have valid predictions loaded,
2) your settings of score_thd, max_det is appropriate, e.g., if score_thd = 1.0, it will filter out all predictions.

**Comment by cyoukaikai** [comment]
Sorry, my previous comment is not correct:  eval_img is 'NoneType', not (eval_img['dtIds'] is 'NoneType').

It seems your settings of detection or gt have problems so that cocoEval is not created correctly.
https://github.com/IIM-TTIJ/MVA2023SmallObjectDetection4SpottingBirds/blob/e7b7b4029a8ae12dcfd197dd72fa7ba92e9dc264/mmdet/datasets/drone.py#L322

**Comment by cyoukaikai** [comment]
We will close this issue. Please leave a comment if you have further questions.
