### ISSUE TITLE
Download Issue!!!

### ISSUE THREAD

**Issue by subecky** [IIM-TTIJ/MVA2023SmallObjectDetection4SpottingBirds#5]
I am having a problem while downloading drone2021.zip file. The download is stopped after downloading around 35GB of the file, throwing the message "Failed - Network error". I try to download it using google chrome and Microsoft edge browsers. I would be very grateful if anyone could provide a suggestion. Thank you very much.

**Comment by Yuki-11** [comment]
Dear subecky,

Thank you for participating in this challenge.
We apologize for any inconvenience you may have experienced in downloading the dataset.
I tried it in my environment and it downloaded successfully, although it took about 50 minutes.

Could you please refer to the following article and try downloading again?
https://bytesbin.com/how-to-download-a-large-file-from-google-drive-quickly/?amp=1 

Regards,

**Comment by subecky** [comment]
Thank you very much. I have downloaded the file successfully.

**Comment by Yuki-11** [comment]
I'm glad you were able to solve your problem.
I hope you enjoy this competition!
