### ISSUE TITLE
tti/test.py is missing

### ISSUE THREAD

**Issue by rsobt** [IIM-TTIJ/MVA2023SmallObjectDetection4SpottingBirds#6]
Thank you for preparing the baseline code.

As mentioned in the subject, tti/test.py is missing.
I would appreciate it if you could add it.

Thank you very much.

* Code in which tti/test.py is used
https://github.com/IIM-TTIJ/MVA2023SmallObjectDetection4SpottingBirds/blob/76ce1017bbc6087226a3a548cbf0a35c88047616/dist_train_test.sh#L30

**Comment by cyoukaikai** [comment]
Sorry, these files were mistakenly removed. 
Thank you very much for your feed. 
Now they are uploaded.

**Comment by rsobt** [comment]
Thank you for your prompt response.
We have resolved the issue and will close it.
