### ISSUE TITLE
Download Issue!!!

### ISSUE THREAD

**Issue by Xiaomang103** [IIM-TTIJ/MVA2023SmallObjectDetection4SpottingBirds#8]
Hello, can you split the drone2021. zip? It's too big. The download is always disconnected, so I have to download it again.

**Comment by Yuki-11** [comment]
Hi @Xiaomang103 ,

Thank you for contacting us.
Have you already tried this solution?
#5 

If the problem persists, please contact us.

**Comment by WooXinyi** [comment]
> 

The Access Token will expire in 1 hour, but we cannot finish downloading the drone2021.zip within 1 hour. So please split the drone2021.zip, thanks!

**Comment by Yuki-11** [comment]
Thank you for reporting the problem.
Please wait for a while as we will prepare it now.

**Comment by Yuki-11** [comment]
We have released a split version of drone2021 below. We hope you will find it useful.
https://drive.google.com/drive/folders/14ouQi32VUQGFkfcipab14fCzBAZ5SzJH?usp=share_link

This issue has been resolved and we are closing this issue.
